// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQGOObT1i4bhAIbGnZm-0ENasaKqHjcIo',
    appId: '1:222578891689:web:828bc07fdd928e3f8842b8',
    messagingSenderId: '222578891689',
    projectId: 'izi-app-360521',
    authDomain: 'izi-app-360521.firebaseapp.com',
    storageBucket: 'izi-app-360521.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7khIYN0alJVMcLAaghO_4pY1zxG_hrkE',
    appId: '1:222578891689:android:6320667178b7a92d8842b8',
    messagingSenderId: '222578891689',
    projectId: 'izi-app-360521',
    storageBucket: 'izi-app-360521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdke_clvsVKz8sRmzTxwmmiF-L6F54Jz4',
    appId: '1:222578891689:ios:11d5195f3aca0bc98842b8',
    messagingSenderId: '222578891689',
    projectId: 'izi-app-360521',
    storageBucket: 'izi-app-360521.firebasestorage.app',
    iosBundleId: 'com.izisoluciones.kiosco.iziKiosco',
  );

}