// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxCpBi8JLQZkAf27-UGJZoS_8F0QO7DOI',
    appId: '1:130455241774:web:03bd2a42eea271be54cbbf',
    messagingSenderId: '130455241774',
    projectId: 'izi-kiosk-prod',
    authDomain: 'izi-kiosk-prod.firebaseapp.com',
    storageBucket: 'izi-kiosk-prod.firebasestorage.app',
    measurementId: 'G-CN7ZFRLY70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBNISJd8yJVJyni-cXqhaktBYkLQPj6Lk',
    appId: '1:130455241774:android:4de7e71fbe64391654cbbf',
    messagingSenderId: '130455241774',
    projectId: 'izi-kiosk-prod',
    storageBucket: 'izi-kiosk-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDToLltOv4K5ZwNhtmCzTEE3nBjA2L1CfM',
    appId: '1:130455241774:ios:309e613654727dc354cbbf',
    messagingSenderId: '130455241774',
    projectId: 'izi-kiosk-prod',
    storageBucket: 'izi-kiosk-prod.firebasestorage.app',
    iosBundleId: 'com.izisoluciones.kiosco.iziKiosco',
  );
}
